name: parser

services:
  parser:
    container_name: parser
    build: .
    volumes:
      - ${LOCATION:-./app_data}:/app_data/files
    env_file:
      - .env
    environment:
      TOKEN_TELEGRAM_BOT: ${TOKEN_TELEGRAM_BOT}
    restart: on-failure
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - '27017:27017'
    volumes:
      - ${LOCATION:-./app_data}/dbdata6:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
  app_data: