name: parser

services:
  parser:
    container_name: parser
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ${LOCATION:-./app_data}:/app_data/files
      - ${LOCATION:-./app_data}/telegram_user.db:/app_data/telegram_user.db:rw
    env_file:
      - .env
    environment:
      TZ: Europe/Moscow
      TOKEN_TELEGRAM_BOT: ${TOKEN_TELEGRAM_BOT}
    restart: on-failure

volumes:
  app_data: