name: parser

services:
  db:
    image: postgres:latest
    volumes:
      - ${LOCATION:-./app_data}/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-parser}
    ports:
      - "5435:5432"
    restart: always
    networks:
      - default

  parser:
    container_name: parser
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ${LOCATION:-./app_data}:/app_data/files
      - ${LOCATION:-./app_data}/telegram_user.db:/app_data/telegram_user.db:rw
    env_file:
      - .env
    command: sh -c "alembic upgrade head && poetry run parser"
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres+asyncpg://postgres:postgres@db:5432/parser}
      TZ: Europe/Moscow
      TOKEN_TELEGRAM_BOT: ${TOKEN_TELEGRAM_BOT}
    restart: on-failure
    networks:
      - default

networks:
  default:
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.35.0.0/16

volumes:
  app_data: