name: parser

services:
  parser:
    container_name: parser
    build: .
    volumes:
      - ${LOCATION:-./app_data}:/app_data/files
    env_file:
      - .env
    environment:
      TOKEN_TELEGRAM_BOT: ${TOKEN_TELEGRAM_BOT}
    restart: on-failure

volumes:
  app_data: