"""change tables

Revision ID: 35a187c6d7ab
Revises: fe76463e41a8
Create Date: 2024-12-03 15:08:22.923030

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35a187c6d7ab'
down_revision: Union[str, None] = 'fe76463e41a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'messages',
        'telegram_user_id',
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        'messages', 'url', existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        'price_history',
        'product_id',
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        'price_history',
        'price',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        'price_history',
        'price_ozon',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        'price_history',
        'original_price',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        'products', 'message_id', existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        'products', 'available', existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        'products', 'url', existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        'products', 'product_name', existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        'products', 'picture', existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        'products',
        'latest_price',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        'products',
        'latest_price_ozon',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        'products',
        'original_price',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'products',
        'original_price',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        'products',
        'latest_price_ozon',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        'products',
        'latest_price',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        'products', 'picture', existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        'products', 'product_name', existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        'products', 'url', existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        'products', 'available', existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        'products', 'message_id', existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        'price_history',
        'original_price',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        'price_history',
        'price_ozon',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        'price_history',
        'price',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        'price_history', 'product_id', existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        'messages', 'url', existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        'messages',
        'telegram_user_id',
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###
