"""change type field

Revision ID: 4687bdf6681b
Revises:
Create Date: 2024-12-01 14:19:08.767795+03:00

"""

from typing import Sequence, Union


from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4687bdf6681b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('messages_telegram_user_id_key', 'messages', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        'messages_telegram_user_id_key', 'messages', ['telegram_user_id']
    )
    # ### end Alembic commands ###
