"""initial

Revision ID: 6520eb12e187
Revises:
Create Date: 2024-12-01 19:47:07.983359+03:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6520eb12e187'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'messages',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('telegram_user_id', sa.Integer(), nullable=True),
        sa.Column('url', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('url'),
    )
    op.create_table(
        'products',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('message_id', sa.Integer(), nullable=True),
        sa.Column('available', sa.Boolean(), nullable=True),
        sa.Column('url', sa.String(), nullable=True),
        sa.Column('product_name', sa.String(), nullable=True),
        sa.Column('picture', sa.String(), nullable=True),
        sa.Column('latest_price', sa.Float(), nullable=True),
        sa.Column('latest_price_ozon', sa.Float(), nullable=True),
        sa.Column('original_price', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ['message_id'],
            ['messages.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'price_history',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('price', sa.Float(), nullable=True),
        sa.Column('price_ozon', sa.Float(), nullable=True),
        sa.Column('original_price', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ['product_id'],
            ['products.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_history')
    op.drop_table('products')
    op.drop_table('messages')
    # ### end Alembic commands ###
