"""add field store

Revision ID: fe76463e41a8
Revises: 6520eb12e187
Create Date: 2024-12-02 16:59:37.011151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe76463e41a8'
down_revision: Union[str, None] = '6520eb12e187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('store', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'store')
    # ### end Alembic commands ###
